FORMAT: 1A

# LendingFront API

The LendingFront API is a simple REST based API that allows you to submit application, data source, decision, underwriting and advance/loan requests to LendingFront's platform.

### Authentication

```no-highlight
LendingFront's APIs use token based authentication. 

LendingFront will provide you with the key which needs be included in all requests.

API calls must be sent via https (SSL)
``` 

### Testing Host

During the implementation phase, LendingFront will provide you with the test and production URLs.

# Data Structures

## ApplicationData
+ key: eyJ24343iOiJIUzI1NiIsImV4cCI6MTQzNjk4NTA3MSwiaWF0Ijo (required) - API Key assigned by LendingFront
+ name: Super Deli (required) - Business name
+ tax_id: 876675543 (required) - The 9 digit Tax ID or EIN
+ phone: 2123455456 (required) - Main business phone 
+ address: 450 5th Ave 3rd Floor (required) - Address line
+ city: New York (required) - City 
+ state: NY (required) - State (NY, NJ, etc)
+ zipcode: 10019 (required) - Postal code

# ApplicationList (array[ApplicationData])

# Group Resources

## Application  [/application]



### Create New Application [POST]

Fields marked with * are required.

#### Attributes

Name | Description | Restrictions 
---- | ----------- | ------------
key* | API Key assigned by LendingFront (send in header - see Request below)
business_name* | Business name
tax_id* | Tax ID or EIN | 9 digits, without dashes, spaces or parenthesis
business_phone* | Main business phone | Without dashes, spaces or parenthesis
business_address* | Business Address line
business_city* | City 
business_state* | State | Two letters: NY, NJ, etc
business_zipcode* | Postal code
bank_account_source* | 1 = Send Bank Enrollment Link<br>2 = Manual Bank Statements<br>3 = Not Required
owners* | See the 'Owners information' section below
industry_type | Business industry type
mailing_address | Business mailing address 
mailing_city | Business mailing city
mailing_state | Business mailing state | Two letters: NY, NJ, etc
mailing_postal_code | Business mailing postal code
average_monthly_sales | Average monthly sales amount
bank_account_number | Business operating bank account number
bank_routing_number | Business operating bank account routing number
legal_entity_type | Corporation, Sole Propriertorship, LLC, Limited Partnership, Partnership, LLC, Other
requested_amount | Request Loan/Advance amount
years_business | Number of years in business | Number of years (e.g 2, 3)
origination_id | The application number of the application in your (CRM) system. 
channel | ISO or Direct
channel_email | ISO email address | Required if channel = ISO
contact_name | ISO contact name | Required if channel = ISO
secondary_iso_name | Name of referring ISO
mobile_phone | Business mobile phone | Without dashes, spaces or parenthesis
state_of_incorporation | The 2 letter state abbreviation where the business was incorporated | Two letters: NY, NJ, etc
 
#### Owners information

An array named 'owners' must be sent. Every item on the array represents an owner and must contain the following params.
However, the previous API that received only one owner is still supported.

Name | Description | Restrictions 
---- | ----------- | ------------
first_name* | First Name of the owner
last_name* | Last Name of the owner
birthday* | Birthday of the owner | format mm/dd/yyyyfix
phone* | Primary phone number of the owner| Without dashes, spaces or parenthesis
mobile_phone | Primary mobile  mophone number of the owner| Without dashes, spaces or parenthesis
ssn* | Social security number | 9 digits, without dashes, spaces or parenthesis
email* | E-mail address used for loan related communications including sending and signing loan docs
city* | City where the owner's home is located
state* | State where the owner's home is located | Two letters: NY, NJ, etc
address* | Owner's home Address
zipcode* | Owner's home Postal Code
title | Owner's title
ownership | Owner's percentage of ownership in the business | Only numbers (e.g '90', '85')


+ Request (application/json)

    + Headers

            Authorization: bearer eyJ24343iOiJIUzI1NiIsImV4cCI6MTQzNjk4NTA3MSwiaWF0Ijo

    + Body

            { 
              'tax_id': '231232131',
              'business_name': 'Super Deli Stores, Inc',
              'dba': 'Super Deli',
              'business_phone': '2123233445',
              'business_address': '400 5th Ave',           
              'business_city': 'New York',
              'business_state': 'NY',
              'business_zipcode': '10019',
              'mailing_address': '400 5th Ave',               
              'mailing_city': 'New York', 
              'mailing_state': 'NY', 
              'mailing_postal_code': '10019', 
              'average_monthly_sales': 175000, 
              'bank_account_number': '45676778', 
              'bank_routing_number': '021000089', 
              'years_business': 1.2,
              'legal_entity_type': 'Corporation',
              'industry_type': 'Food and services',
              'requested_amount': '25000', 
              'origination_id': '456700',
              'bank_account_source': 1,
              'state_of_incorporation': 'DE',
              'mobile_phone': '2014565678',
              'owners': [
                {
                  'email': u'petersmith@gmail.com', 
                  'first_name': 'Peter',               
                  'last_name': 'Smith',
                  'title': 'Dr',
                  'ownership': '90', 
                  'ssn': '123256789',               
                  'phone': u'3475608900',               
                  'address': '450 E 45th Street',               
                  'city': 'New York',               
                  'state': 'NJ', 
                  'zipcode': '07047',               
                  'birthday': '1/1/1975'
                },
                {
                  'email': u'secondowner@gmail.com', 
                  'first_name': 'Matt',               
                  'last_name': 'Simon',
                  'title': 'Dr',
                  'ownership': '10', 
                  'ssn': '987654321',
                  'phone': u'2124345554',
                  'address': '450 E 45th Street',
                  'city': 'San Francisco',
                  'state': 'CA', 
                  'zipcode': '94122',               
                  'birthday': '1/1/1980'
                }
              ]
            }
            

+ Response 200 (application/json)

        + Success  
    
            {
                'status': 'OK',
                'display_status': 'APPLICATION RECEIVED',
                'application': [application id],
                'application_number': [application number],
                'business': [business id]
            }

        + Error  
    
            {
                'status': 'ERROR',
                'message': [error message]
            }

        + Duplicate  
    
            {
              'status': 'WARN',
              'message': 'A duplicate application was found. Your application has not been created'
            }

+ Attributes (ApplicationData)


### Get Application [GET]
Retrieves an application by application_number.

#### Attributes

Name | Description
---- | -----------
key | API Key assigned by LendingFront (send in header - see Request below)
application_number | Unique number that identifies a submitted application. This number is returned by the create application endpoint.

+ Request  (application/json)

    + Headers

            Authorization: bearer eyJ24343iOiJIUzI1NiIsImV4cCI6MTQzNjk4NTA3MSwiaWF0Ijo


    + Body

            {
                application_number: '196415838638'
            }

+ Response 200 (application/json)

        +  success
        
                {
                    'status': 'OK',
                    'application': {
                        'id': [application id],
                        'application_number': [application number],
                        'status': [status],
                        'business_id': [business id],
                        'cents_on_the_dollar': [cents on the dollar],
                        'channel': [ISO or Direct],
                        'city': [city],
                        'client_id': [client id],
                        'create_date': [date],
                        'daily_payment': [daily payment],
                        'decision': [decision],
                        'decision_date': [date],
                        'docs_received_date': [date],
                        'docs_sent_date': [date],
                        'frequency_name': [frequency name],
                        'iso_contact_email': [email],
                        'iso_contact_name': [name],
                        'iso_name': [name],
                        'iso_secondary_name': [name],
                        'loan_amount': [loan amount],
                        'name': [name],
                        'origination_fee': [fee],
                        'origination_id': [origination id],
                        'owner_id': [owner id],
                        'payment_day': [payment day],
                        'payment_day_number': [payment day number],
                        'payment_frequency': [payment frequency],
                        'payment_frequency_id': [payment frequency_id],
                        'phone': [phone],
                        'product_type': [product type],
                        'purchased_amount': [purchased amount],
                        'requested_amount': [requested amount],
                        'specified_percentage': [specified percentage],
                        'state': [state],
                        'term': [term],
                        'total_number_payments': [total number payments],
                        'underwriting_date': [date],
                        'waiting_for_bank_verification_date': [date]
                    }
                }
                
        +  Not Found 
        
                {
                    'status': 'OK',
                    'message': 'Application not found'
                }
        
        +  Error 
        
                {
                    'status': 'ERROR',
                    'message': 'An error ocurred while processing the request'
                }

+ Attributes
        application_number: '100456' (required)


## Application Status Change Notification [/providedbylender]

### Application status change - Callback [POST]
Applications status change notifications will be POST to the callback URL you provide to LendingFront during the implementation process.

A separate response is returned when the application is initially created which includes the LendingFront application number (see application/create api above).

The notification call can send a security token or user credentials depending on the security mechanism implemented by your API.


#### Attributes

Name | Description
---- | -----------
application_number | Unique number assigned to the application when it was created
origination_id|Application ID in your CRM software (optional)
old_status|Previous application status
new_status|New application status

#### Optional attributes (key or username/password)

Name | Description
---- | -----------
key|API key assigned by the lender for token based authentication  
username|username of lender's API if basic authentication is used
password|lender's API password


+ Request (application/json)


    + Body

            { 
              application_number: 231232131,
              old_status: 'APPLICATION_RECEIVED',
              new_status: 'UNDERWRITING',
              origination_id: 1230492
              }