FORMAT: 1A

# LendingFront API

The LendingFront API is a simple REST based API that allows you to submit application, data source, decision, underwriting and loan requests to LendingFront's platform.

Our platform collects Social, Cash Flow and Credit Bureau data electronically.
It is important that the business owner agrees to the terms and conditions before requests are submitted.

### Authentication

```no-highlight
LendingFront's APIs use token based authentication. You can get a key in the Settings page of the 
LendingPortal. The setting page is only available to Administrator users.

During the initial pilot, LendingFront will manually provide you with a key.

API calls must be sent via https (SSL)
``` 

### Testing Host

During the implementation phase, LendingFront will provide the test and production URLs.

# Data Structures

## ApplicationData
+ key: eyJ24343iOiJIUzI1NiIsImV4cCI6MTQzNjk4NTA3MSwiaWF0Ijo (required) - API Key assigned by LendingFront
+ name: Super Deli (required) - Business name
+ tax_id: 876675543 (required) - The 9 digit Tax ID or EIN
+ phone: 2123455456 (required) - Main business phone 
+ address: 450 5th Ave 3rd Floor (required) - Address line
+ city: New York (required) - City 
+ state: NY (required) - State (NY, NJ, etc)
+ zipcode: 10019 (required) - Postal code

# ApplicationList (array[ApplicationData])

# Group Resources

## Application  [/application]


### Get Application [GET]
Retrieves an application by application_number.

Attributes:

Name | Description
---- | -----------
key | API Key assigned by LendingFront
application_number | Unique number that identifies a submitted application. This number is returned by the create application endpoint.

+ Request  (application/json)

    + Headers

            Authorization: bearer eyJ24343iOiJIUzI1NiIsImV4cCI6MTQzNjk4NTA3MSwiaWF0Ijo


    + Body

            {
                application_number: '196415838638'
            }

+ Response 200 (application/json)

        +  success
        
                {
                    'status': 'OK',
                    'application_number':'196415838638',
                    'requested_amount':Decimal('54000'),
                    'loan_amount': Decimal('45000'),
                    'origination_id': '345433',
                    'term': 6,
                    'origination_fee':,
                    'cents_on_the_dollar': Decimal('0.15'),
                    'decision': 'APPROVED',
                    'status': 'FUNDED',
                    'create_date': '07/13/2015',
                    'decision_date': '07/13/2015'
                }
                
        +  Not Found 
        
                {
                    'status': 'OK',
                    'message': 'Application not found'
                }
        
        +  Error 
        
                {
                    'status': 'ERROR',
                    'message': 'An error ocurred while processing the request'
                }

+ Attributes
        application_number: '100456' (required)

### Create New Application [POST]
Create New Application

Attributes:

Name | Description
---- | -----------
key | API Key assigned by LendingFront
business_name | Business name
tax_id | The 9 digit Tax ID or EIN
business_phone | Main business phone 
business_address | Address line
business_city | City 
business_state | State (NY, NJ, etc)
business_zipcode | Postal code
 
Owner information:

Name | Description
---- | -----------
first_name | First Name of the primary owner
last_name | Last Name of the primary owner
birthday | Birthday of the primary owner
owner_phone | Primary phone number of owner
ssn | Last 4 digits of the social security number
owner_email | E-mail address used for loan related communications including sending and signing loan docs
owner_city | City where the owner's home is located
owner_state | State where the owner's home is located
owner_address | Owner's home Address 
owner_zipcode | Owner's home Postal Code

Optional Fields:

Name | Description
---- | -----------
years_business | Number of years in business (e.g 2, 3)
estimated_annual_revenue | Self provided annual revenue 
origination_id | The application number of the application in your (CRM) system. 
send_link | True if a bank enrollment email should be sent to the business to connect their Operating bank account to LendingFront's platform

+ Request (application/json)

    + Headers

            Authorization: bearer eyJ24343iOiJIUzI1NiIsImV4cCI6MTQzNjk4NTA3MSwiaWF0Ijo

    + Body

            { 
              'tax_id': '231232131',               
              'business_name': 'Data Service 12',  
              'business_phone': '2123233445', 
              'business_address': '400 5th Ave',               
              'business_city': 'New York', 
              'business_state': 'NY', 
              'business_zipcode': '10019', 
              'owner_email': u'petersmith@gmail.com', 
              'first_name': 'Peter',               
              'last_name': 'Smith', 
              'ssn': '1232',               
              'owner_phone': u'3475608900',               
              'owner_address': '450 E 45th Street',               
              'owner_city': 'New York',               
              'owner_state': 'NJ', 
              'owner_zipcode': '07047',               
              'birthday': '1/1/1975',
              'requested_amount': '25000', 
              'origination_id': '456700',               
              'send_link': 'True'
            }
            



+ Response 200 (application/json)

        + Success  
    
            { 'status': 'OK',
              'application_number': '1234567890'
            }

        + Error  
    
            {
              'status': 'ERROR',
              'message': [error message]
            }

        + Duplicate  
    
            {
              'status': 'WARN',
              'message': 'A duplicate application was found. Your application was not created'
            }

+ Attributes (ApplicationData)

## Decision Engine [/decision]

### Get Decision [GET]
Retrieves a decision by application_number.

Attributes:

Name | Description
---- | -----------
key | API Key assigned by LendingFront
application_number | Unique number that identifies an application. This number is returned by the create application endpoint.


+ Request  (application/json)

    + Headers

            Authorization: bearer eyJ24343iOiJIUzI1NiIsImV4cCI6MTQzNjk4NTA3MSwiaWF0Ijo


    + Body

            {
                application_number: '196415838638'
            }

+ Response 200 (application/json)

        +  approve
        
            {
                "status": "OK",
                "active_status": "ACTIVE",
                "recommendation": "APPROVE",
                "risk_level": "HIGH",
                "score_list": { 
                    "custom_score": 750,
                    "fico": 800,
                    "lf_score": 500
                },
                "loan_amount": {
                    "min": 0,
                    "max": 45000,
                    "recommended": 22500
                },
                "pricing": {
                    "min": 0,
                    "max": 100,
                    "recommended": 45
                },
                "term": { 
                    "min": 1,
                    "max": 12,
                    "recommended": 6
                },
                "reasons": {}
            }
            
        +  decline
        
            {
                "status": "OK",
                "active_status": "ACTIVE",
                "recommendation": "DECLINE",
                "risk_level": "HIGH",
                "score_list": { 
                    "custom_score": 750,
                    "fico": 800,
                    "lf_score": 500
                },
                "loan_amount": {
                    "min": 0,
                    "max": 45000,
                    "recommended": 22500
                },
                "pricing": {
                    "min": 0,
                    "max": 100,
                    "recommended": 45
                },
                "term": { 
                    "min": 1,
                    "max": 12,
                    "recommended": 6
                },
                "reasons": [
                    "Income is too low",
                    "Too many credit cards"
                ]
            }
        
        +  undecided
        
            {
                "status": "OK",
                "active_status": "ACTIVE",
                "recommendation": "UNDECIDED",
                "risk_level": "HIGH",
                "score_list": { 
                    "custom_score": 750,
                    "fico": 800,
                    "lf_score": 500
                },
                "reasons": {}
            }

+ Attributes
        application_number: '100456' (required)

## Data Service  [/dataservice]

### Pull social data [POST]
Pulls social data for the given application.

Attributes:

Name | Description
---- | -----------
key | API Key assigned by LendingFront
application_number | Unique number that identifies an application. This number is returned by the create application endpoint.


+ Request  (application/json)

    + Headers

            Authorization: bearer eyJ24343iOiJIUzI1NiIsImV4cCI6MTQzNjk4NTA3MSwiaWF0Ijo


    + Body

            {
                application_number: '196415838638'
            }

+ Response 200 (application/json)

        +  success
        
            {
                "status": "OK",
                "google_status": "OK",
                "yelp_status": "OK",
                "website": "www.flavorsnyc.com",
                "end_date": "05/22/2015",
                "price_level": 1,
                "category": "Restaurant & Bar",
                "business_id": 51,
                "phone": "+1 212-668-9800",
                "id": "OK",
                "message": "SUCCESS",
                "address": "74 Broad St, New York, NY 10004",
                "category": ["Restaurant & Bar"],
                "ratings": {
                    "detail": {
                        "01/08/2015": 4,
                        "02/07/2015": 5,
                        "03/17/2015": 3,
                        "04/16/2015": 4,
                        "05/18/2015": 5
                    },
                    "summary": {
                        "total_ratings": 21,
                        "average_rating": 4,
                        "monthly": {
                            "February": {
                                "count": 2,
                                "index": 3,
                                "score":8.0
                            },
                            "March": {
                                "count": 3,
                                "index": 2,
                                "score":5.0
                            },
                            "May": {
                                "count": 2,
                                "index": 0,
                                "score":3.0
                            },
                            "December": {
                                "count": 4,
                                "index": 5,
                                "score":9.0
                            },
                            "April": {
                                "count": 3,
                                "index": 1,
                                "score":0.0
                            },
                            "January": {
                                "count": 2,
                                "index": 4,
                                "score":1.0
                            },
                            "November": {
                            "count": 5,
                            "index": 6,
                            "score":5.0
                            }
                        }
                    }
                },
                "current_rating": 4.1,
                "longitude": -74.011829,
                "reviews": {
                    "count_negatives":2,
                    "count_positives":13
                },
                "latitude": 40.704655,
                "start_date": "11/22/2014"
            }

### Get social data [GET]
Get previously pulled social data

Attributes:

Name | Description
---- | -----------
key | API Key assigned by LendingFront
application_number | Unique number that identifies an application. This number is returned by the create application endpoint.


+ Request  (application/json)

    + Headers

            Authorization: bearer eyJ24343iOiJIUzI1NiIsImV4cCI6MTQzNjk4NTA3MSwiaWF0Ijo

    + Body

            {
                application_number: '196415838638'
            }

+ Response 200 (application/json)

        +  success
        
            {
                "status": "OK",
                "google_status": "OK",
                "yelp_status": "OK",
                "website": "www.flavorsnyc.com",
                "end_date": "05/22/2015",
                "price_level": 1,
                "category": "Restaurant & Bar",
                "business_id": 51,
                "phone": "+1 212-668-9800",
                "id": "OK",
                "message": "SUCCESS",
                "address": "74 Broad St, New York, NY 10004",
                "category": ["Restaurant & Bar"],
                "ratings": {
                    "detail": {
                        "01/08/2015": 4,
                        "02/07/2015": 5,
                        "03/17/2015": 3,
                        "04/16/2015": 4,
                        "05/18/2015": 5
                    },
                    "summary": {
                        "total_ratings": 21,
                        "average_rating": 4,
                        "monthly": {
                            "February": {
                                "count": 2,
                                "index": 3,
                                "score":8.0
                            },
                            "March": {
                                "count": 3,
                                "index": 2,
                                "score":5.0
                            },
                            "May": {
                                "count": 2,
                                "index": 0,
                                "score":3.0
                            },
                            "December": {
                                "count": 4,
                                "index": 5,
                                "score":9.0
                            },
                            "April": {
                                "count": 3,
                                "index": 1,
                                "score":0.0
                            },
                            "January": {
                                "count": 2,
                                "index": 4,
                                "score":1.0
                            },
                            "November": {
                            "count": 5,
                            "index": 6,
                            "score":5.0
                            }
                        }
                    }
                },
                "current_rating": 4.1,
                "longitude": -74.011829,
                "reviews": {
                    "count_negatives":2,
                    "count_positives":13
                },
                "latitude": 40.704655,
                "start_date": "11/22/2014"
            }

### Pull PayNet  [POST]
Pull PayNet credit report

Attributes:

Name | Description
---- | -----------
key | API Key assigned by LendingFront
application_number | Unique number that identifies an application. This number is returned by the create application endpoint.


+ Request  (application/json)

    + Headers

            Authorization: bearer eyJ24343iOiJIUzI1NiIsImV4cCI6MTQzNjk4NTA3MSwiaWF0Ijo

    + Body

            {
                application_number: '196415838638'
            }

+ Response 200 (application/json)

        +  success
   


